# Generated by Django 2.2.7 on 2019-12-05 06:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_no', models.CharField(max_length=8, unique=True)),
                ('bed_type', models.CharField(max_length=6)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('telephone_line1', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '99999999999'. Minimum 10 to Maximum 14 digits allowed.", regex='^\\+?1?\\d{10,12}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('contact_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '99999999999'. Minimum 10 to Maximum 14 digits allowed.", regex='^\\+?1?\\d{10,12}$')])),
            ],
        ),
        migrations.CreateModel(
            name='WardOrRoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wr_type', models.CharField(max_length=20, unique=True)),
                ('is_ward_type', models.BooleanField()),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_beds', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_no', models.CharField(max_length=8, unique=True)),
                ('floor', models.PositiveIntegerField()),
                ('ward_extension', models.PositiveIntegerField(blank=True, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_building', to='patients.Building')),
                ('wr_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_type', to='patients.WardOrRoomType')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=8, unique=True)),
                ('floor', models.PositiveIntegerField()),
                ('room_extension', models.PositiveIntegerField(blank=True, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_building', to='patients.Building')),
                ('wr_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='patients.WardOrRoomType')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('bed_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_bedno', to='patients.Bed')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_building', to='patients.Hospital'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bed', to='patients.Room'),
        ),
    ]
