# Generated by Django 2.0.4 on 2019-12-07 14:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date_taken', models.DateTimeField()),
                ('appointment_mode', models.CharField(choices=[('By Phone', 'By Phone'), ('By Email', 'By Email'), ('By Self', 'By Self')], default='By Phone', max_length=15)),
                ('appointment_date_time', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('clinical_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_healthprof_dept', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeptManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee_DeptManager_no', to='patients.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_healthprof_desg', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField()),
                ('abbreviation', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoseUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('abbreviation', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('blood_group', models.CharField(choices=[('Not Known', 'Not Known'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=6)),
                ('photo', models.FileField(blank=True, null=True, upload_to='employee_profiles')),
                ('address', models.TextField()),
                ('email_id', models.EmailField(max_length=254)),
                ('telephone_line1', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '99999999999'. Minimum 10 to Maximum 14 digits allowed.", regex='^\\+?1?\\d{10,12}$')])),
                ('joining_date', models.DateField()),
                ('role', models.CharField(choices=[('Health Professional', 'Health Professional'), ('Nurse', 'Nurse'), ('Aaya', 'Aaya'), ('WardBoy', 'WardBoy')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('print_date', models.DateField()),
                ('pay_days', models.IntegerField()),
                ('Income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('prof_tax', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('pf', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('h_rent', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('da', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('other_earning', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('payslip_for_month_of', models.DateTimeField()),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('net_payment', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_no', to='patients.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('expiry_date', models.DateField()),
                ('batch_id', models.CharField(blank=True, max_length=12, null=True)),
                ('dose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dose_Medicament_related', to='patients.Dose')),
                ('doseunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoseUnit_Medicament_related', to='patients.DoseUnit')),
                ('drug_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DrugForm_Medicament_related', to='patients.DrugForm')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card')], max_length=20)),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('healthprofessional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee_MedicamentBill_related', to='patients.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentBillCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicament_MedicamentCharges_related', to='patients.Medicament')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentPackRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicament_MedicamentPackRate_related', to='patients.Medicament')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationDosage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('abbreviation', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MFGCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('abbreviation', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strip_of_tab', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chief_complaints', models.TextField()),
                ('diagnosis', models.TextField()),
                ('blood_pressure', models.CharField(blank=True, default='80/120', max_length=6, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('advice', models.TextField()),
                ('next_followup', models.DateField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment_PatientVisits_related', to='patients.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('other_advice', models.CharField(blank=True, max_length=30, null=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicament_Prescription_related', to='patients.Medicament')),
                ('patientvisits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PatientVisits_Prescription', to='patients.PatientVisits')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('Not Known', 'Not Known'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='Not Known', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientvisits',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_PatientVisits_related', to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='medicamentpackrate',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pack_MedicamentPackRate_related', to='patients.Pack'),
        ),
        migrations.AddField(
            model_name='medicamentcharges',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pack_MedicamentCharges_related', to='patients.Pack'),
        ),
        migrations.AddField(
            model_name='medicamentbillcharges',
            name='medicament_charges',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicament_bill_charges', to='patients.MedicamentCharges'),
        ),
        migrations.AddField(
            model_name='medicamentbill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_MedicamentBill_related', to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='mfg_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MFGCompany_Medicament_related', to='patients.MFGCompany'),
        ),
        migrations.AddField(
            model_name='doseunit',
            name='drugform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DrugForm_DoseUnit_related', to='patients.DrugForm'),
        ),
        migrations.AddField(
            model_name='deptmanager',
            name='desg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Designation_DeptManager_name', to='patients.Designation'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='healthprofessional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HP_Appointment_related', to='patients.Employee'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_Appointment_related', to='patients.Patient'),
        ),
    ]
