# Generated by Django 3.0 on 2019-12-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20191207_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(choices=[('Not Known', 'Not Known'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Health Professional', 'Health Professional'), ('Nurse', 'Nurse'), ('Aaya', 'Aaya'), ('WardBoy', 'WardBoy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('Not Known', 'Not Known'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='Not Known', max_length=15),
        ),
    ]
