# Generated by Django 3.0 on 2019-12-12 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20191211_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='registration_code',
            new_name='reg_code',
        ),
        migrations.AddField(
            model_name='patient',
            name='telephone_line1',
            field=models.CharField(default=0, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '99999999999'. Minimum 10 to Maximum 14 digits allowed.", regex='^\\+?1?\\d{10,12}$')]),
            preserve_default=False,
        ),
    ]
