# Generated by Django 3.0 on 2019-12-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20191216_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
