# Generated by Django 3.0 on 2019-12-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20191216_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientvisits',
            old_name='name',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='patientvisits',
            name='date',
        ),
    ]
