# Generated by Django 3.0 on 2019-12-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20191218_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
