# Generated by Django 3.0 on 2019-12-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_auto_20191219_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
