# Generated by Django 3.0 on 2019-12-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_auto_20191220_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(default=None, upload_to='employee/pics/'),
            preserve_default=False,
        ),
    ]
