# Generated by Django 3.0 on 2019-12-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_auto_20191222_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='photo',
            field=models.FileField(default=0, upload_to='hospital/pics/'),
            preserve_default=False,
        ),
    ]
