# Generated by Django 3.0 on 2019-12-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_hospital_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='photo',
        ),
    ]
