# Generated by Django 3.0 on 2019-12-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_remove_hospital_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, upload_to='employee/pics/'),
        ),
    ]
