# Generated by Django 3.0 on 2019-12-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_auto_20191222_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
    ]
