# Generated by Django 3.0 on 2019-12-22 14:09

from django.db import migrations, models
import patients.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_remove_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='employee/pics/', validators=[patients.validators.validate_image_extension]),
        ),
    ]
