# Generated by Django 3.0 on 2020-01-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_auto_20200107_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationdosage',
            name='abbreviation',
        ),
    ]
